# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c60f7116f3b6a18d6418a4f9e58e902789e3d38c32c92a76890cb68d1ab075b2b69b9d033d5d50982ee36c6975057fd9a69bd8b38581fc4ca0a28f5b282bb1be

test:
  secret_key_base: 5404aab4bf0497036ea67b52b148004b4d02fc7dcb8835d865051418a115bce982f98c0c8a27d1d8a0acf8254023ca684ad1e85e22ead99762e36a911cf9318f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
